### PR TITLE
Issue #109 - Adjust Show password font size 

### LINKED ISSUE #109: Adjust `show password` font size
The `show password` option in the `login` and `signup` page has a different font style and size compared to the other elements on the page. It will great if it has the same style and size as others.

### PR DESCRIPTION
**Pull request by nitinshukla413**
# Changes

Fixes #109 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
- [ ] Attached screenshots of changes made.

### CODE REVIEW

**Comment by siv2r** [comment]
Can you add the screenshots after the change?

**Comment by nitinshukla413** [comment]
Fixes Issue #111 
Before:
image
After change:
image

**Comment by siv2r** [comment]
The font style doesn't seem to match. 
The checkbox and the font size can still be increased. Compare the font size with the `Re-enter Password` and try to keep it slightly smaller than it.

**Comment by nitinshukla413** [comment]
Made changes. Please review it.
image

**Comment by siv2r** [comment]
Great work!!

**Pull request merged**
