### PR TITLE
removed all comments having large size

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
removed all comments having large size

Addresses : #158

### CODE REVIEW

**Comment by arpit456jain** [comment]
Hey @siv2r can you please give me lvl 3 . I know there is lvl 2 label on issue . 
If possible give it lvl 3 otherwise lvl 2 also fine for me

**Comment by siv2r** [comment]
Sure 👍

**Comment by siv2r** [comment]
can you remove the one mentioned in the issue description also?

**Comment by arpit456jain** [comment]
I just closed the laptop 😐
Can i remove it in another issue on some other day?

**Comment by siv2r** [comment]
Sure, No worries

**Pull request merged**
