### PR TITLE
Fixed Issue#94 "Added Brand Logo"

### LINKED ISSUE #94: Missing! Brand logo of the website.

### PR DESCRIPTION
**Pull request by hardikvarshney**
# Changes

Fixes #94 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Attached screenshots of changes made.

### CODE REVIEW

**Comment by hardikvarshney** [comment]
@siv2r Added CSS in style tag. Can you please add level of the issue(i.e. level 3) to this pull request. I don't know how to link a PR with Issue.

**Comment by siv2r** [comment]
Hey, were you able to test the changes?

Attaching a screenshot will be helpful.

**Comment by siv2r** [comment]
If not I will test them later before merging

**Comment by siv2r** [comment]
Any specific reason for closing the PR?

**Pull request closed without merging**
