### PR TITLE
Architecture branch

### PR DESCRIPTION
**Pull request by sahilempire**

### CODE REVIEW

**Comment by siv2r** [comment]
Hey, sorry for not replying sooner. I started writing the `Architecture` branch since the `master` was messy wrt to file placements. 
There has been a lot of new features added to the master so, the `Architecture` branch will probably be abandoned :(

**Comment by sahilempire** [comment]
@siv2r so what I have to do now?

**Comment by siv2r** [comment]
It is better if you start looking for other issues since this will probably be abandoned.

**Comment by siv2r** [comment]
Closing this since, it is not required for this project at this point of time.

**Pull request closed without merging**
