### PR TITLE
added eye icon

### LINKED ISSUE #324: Add show password option to login signup page
In the login and signup page inside the password field we can add and eye icon which when clicked shows the password

### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

### PR DESCRIPTION
**Pull request by ayushseth07**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

fixed #324 

image

### CODE REVIEW

**Comment by siv2r** [comment]
@ayushseth07 I noticed that there is already a `showPassword.js` file. So you can put your new function in this instead of creating a `showPassoword2.js`. 
I asked you to create a new `.js` file last time. Sorry for the wrong suggestion. I didn't know that `showPassword.js` already existed.

Also, you don't need to create a new PR every time. Just update the local branch and `git push` which will automatically update this PR.

**Comment by siv2r** [comment]
@ayushseth07 Everything looks amazing!!
Did you test the working of new changes?

**Comment by ayushseth07** [comment]
@siv2r yes i have tested them and they are working fine

**Comment by siv2r** [comment]
@ayushseth07 Thanks for this amazing PR :tada: :tada:

**Pull request merged**
