### PR TITLE
Width bug in Overview page Fixed

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
Width bug in Overview page

Fixes: #33 

### How did you test your changes?
data

### CODE REVIEW

**Comment by arpit456jain** [comment]
hey @siv2r please review this PR

**Comment by siv2r** [comment]
Things look good. Can you send a screenshot of how this looks if `status` col had the value `Inactive` instead of `1`

**Comment by arpit456jain** [comment]
ss

**Comment by arpit456jain** [comment]
@siv2r

**Comment by arpit456jain** [comment]
@siv2r please add a suitable label to it

**Pull request merged**
