### PR TITLE
Solved Improving Home Page Issue #63

### LINKED ISSUE #63: Improving the home page
The home page is just a simple image. I would like to improve it by  adding something about the inspiration behind the project or something more about the project's usage etc. Can I work on it as a part of GSSoC?

### PR DESCRIPTION
**Pull request by Spurthi7768**
Fixes #63 
@siv2r I have tried improving the home page by changing the background. Any feedback on how it looks?

### CODE REVIEW

**Comment by siv2r** [comment]
can send the screenshot of the homepage?

**Comment by Spurthi7768** [comment]
kidney
@siv2r is it visible?

**Review by siv2r — DISMISSED** [review]

**Comment by siv2r** [comment]
Hey, This looks beautiful!!
This lighter theme seems incoherent with the other pages like signup, search (dark theme) and makes the words on the transparent navigation bar difficult to read (like home, login, sign up).

Can you make it have a darker theme?

**Comment by Spurthi7768** [comment]
@siv2r I have tried to include a dark theme.. please check it out once!
kidney_1

**Comment by Spurthi7768** [comment]
@siv2r any feedback?

**Comment by Spurthi7768** [comment]
@siv2r  I am posting a screenshot first.. if it is okay then I will create a pull request for it!
kidney_2

**Comment by siv2r** [comment]
This is great!! You can send the PR :)

**Comment by Spurthi7768** [comment]
@siv2r here is the PR! If any more changes let me know!

**Pull request merged**
