### PR TITLE
Responsiveness of REGISTRATION FORM Page i.e (reg-form.php)

### PR DESCRIPTION
**Pull request by arpit456jain**
### What does this implement/fix? Explain your changes.
of REGISTRATION FORM Page i.e (reg-form.php)

Fixes : #167 

### How did you test your changes?
Previously
screencapture-localhost-kidney-exchange-pages-reg-form-php-2021-05-15-09_46_42

after my changes
screencapture-localhost-kidney-exchange-pages-reg-form-php-2021-05-15-09_45_51
screencapture-localhost-kidney-exchange-pages-reg-form-php-2021-05-15-09_43_33

### CODE REVIEW

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/118347726-0da15a00-b563-11eb-9d19-c3af796e3765.mp4

**Comment by arpit456jain** [comment]
@siv2r please review this PR

**Comment by arpit456jain** [comment]
screencapture-localhost-kidney-exchange-pages-reg-form-php-2021-05-15-21_29_10

**Comment by siv2r** [comment]
This PR looks Amazing!!
**Suggested Changes** (for the desktop view)
- In the HLA antigen field, It would be better if A is to the left of the input field instead of on the top
- all the input field be of the same length or at least start from the same margin (from the left)

**Comment by arpit456jain** [comment]
Ok @siv2r i will try to do it 
But i am not sure that it's possible or not but i will surely try once or the 2nd option is to remove all css for it and add bootstrap classes but it will take a lots of changes that's why i am avoiding it

**Comment by siv2r** [comment]
> 2nd option is to remove all css for it and add bootstrap classes but it will take a lots of changes

Yes, It would be better if this is not the case.

**Comment by arpit456jain** [comment]
@siv2r will this form work for now?

**Comment by arpit456jain** [comment]
I mean i will try both the methods and if its looking good i will tell you

**Comment by arpit456jain** [comment]
Because if i add bootstrap classes and removed all css there will no red background colour on invalid input 

And it will take at least 2 to 3 days since it's a very long form lots and lots of input tags

**Comment by siv2r** [comment]
> @siv2r will this form work for now?

Okay, I will merge this now.

**Comment by arpit456jain** [comment]
> > @siv2r will this form work for now?
> 
> Okay, I will merge this now.

I will definitely work on this side by side ans update you soon

**Pull request merged**
