### PR TITLE
Added docstrings for the functions

### PR DESCRIPTION
**Pull request by madihamallick**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### Any relevant logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### Any other comments?
....

### CODE REVIEW

**Comment by siv2r** [comment]
Do not replace the print functions. You could add an empty docstring that has details about parameters and the return type of the functions. 
If you are using `vscode,` then the extension `Python Docstring Generator` does this. 
Here is the link to it: https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring

**Comment by madihamallick** [comment]
> Python Docstring Generator

Sure I'll do the changes

**Comment by siv2r** [comment]
Also the docstrings are ideally added to **function definition** and **classes**

**Comment by madihamallick** [comment]
> Also the docstrings are ideally added to **function definition** and **classes**

@siv2r Please check now

**Comment by siv2r** [comment]
How were the `docstrings` generated? Your docstring misses the information on function arguments. 
Example: (when using the docstring generator)
```python3
def optimize_length(cycles,vertices,dirname, coef=[], ilp=True):
	"""[summary]

	Args:
		cycles ([type]): [description]
		vertices ([type]): [description]
		dirname ([type]): [description]
		coef (list, optional): [description]. Defaults to [].
		ilp (bool, optional): [description]. Defaults to True.

	Returns:
		[type]: [description]
	"""
```

Also, you don't need to write a summary, description of function arguments, and return type. I will do them later :)

**Comment by madihamallick** [comment]
> How were the `docstrings` generated? Your docstring misses the information on function arguments.
> Example: (when using the docstring generator)
> 
> ```python
> def optimize_length(cycles,vertices,dirname, coef=[], ilp=True):
> 	"""[summary]
> 
> 	Args:
> 		cycles ([type]): [description]
> 		vertices ([type]): [description]
> 		dirname ([type]): [description]
> 		coef (list, optional): [description]. Defaults to [].
> 		ilp (bool, optional): [description]. Defaults to True.
> 
> 	Returns:
> 		[type]: [description]
> 	"""
> ```
> 
> Also, you don't need to write a summary, description of function arguments, and return type. I will do them later :)

yes for this function arguments are showing, I did it in the same way  for `precomputation.py` file but it is not showing there.

**Comment by madihamallick** [comment]
Done @siv2r :)

**Comment by siv2r** [comment]
Great work :tada: :tada:

**Pull request merged**
