### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kanchi12P**
I have made some changes
Please review them and tell me if any more changes you want I would like to do that.

### CODE REVIEW

**Comment by siv2r** [comment]
Can you attach a screenshot?

**Comment by kanchi12P** [comment]
> Can you attach a screenshot?
**attached 5 screenshots**
1
Screenshot (8604)

2

Screenshot (8605)

3

Screenshot (8606)

4

Screenshot (8607)

5

Screenshot (8608)

**Comment by kanchi12P** [comment]
@siv2r  added screenshots

**Comment by siv2r** [comment]
Wow!! Looks Amazing!! I will merge it soon :)

**Comment by kanchi12P** [comment]
Thank you!

**Pull request merged**
