### PR TITLE
added auto assign bot

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
added auto assign bot

### Does this close any currently open issues?
#142 

### How did you test your changes?
On my repo on GitHub

### CODE REVIEW

**Comment by arpit456jain** [comment]
@siv2r kindly merge this PR

**Comment by siv2r** [comment]
Will the participant be able to assign the issues to themselves using this?

**Comment by arpit456jain** [comment]
> Will the participant be able to assign the issues to themselves using this?

Yes it should

**Comment by arpit456jain** [comment]
Just have to write /assign

**Comment by arpit456jain** [comment]
I had uploaded a demo video in issue section in morning did you see that @siv2r

**Comment by siv2r** [comment]
I saw only the first minute so I missed the auto assign demo

**Comment by siv2r** [comment]
Everything looks good! Great work 🎉

**Comment by arpit456jain** [comment]
> I saw only the first minute so I missed the auto assign demo

No problem let's see if it works or not
Fingers crossed 🤞

**Comment by siv2r** [comment]
@arpit456jain, Can you check auto assign with any issue after I merge this? Also, could you tag me in that message?

**Comment by arpit456jain** [comment]
> @arpit456jain, Can you check auto assign with any issue after I merge this? Also, could you tag me in that message?

Yes sure

**Pull request merged**
