### PR TITLE
added required to input fields

### PR DESCRIPTION
**Pull request by arpit456jain**
added required to input fields

Fixes : #234

### CODE REVIEW

**Comment by arpit456jain** [comment]
@siv2r please review this PR

**Comment by siv2r** [comment]
The validation for this has been done in PHP so, this is not necessary.

**Comment by arpit456jain** [comment]
> The validation for this has been done in PHP so, this is not necessary.

But @siv2r its good practice to put required attribute . It can cause server error. Let me explain


Let's assume this website is hosted anyone can easily create pressure on server by submitting again n again.
At the end server will collapse

So in my suggestion if we can handle null fields in front end then we should @siv2r

**Comment by arpit456jain** [comment]
@siv2r please merge this PR i don't think there is harm to put required

**Pull request closed without merging**
