### PR TITLE
fixed the footer in displayGlobalMatch.php

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
fixed the footer in displayGlobalMatch.php

Fixes : #194

### How did you test your changes?
sol3

### CODE REVIEW

**Comment by arpit456jain** [comment]
img s not present on the folder that's why its not showing

**Comment by arpit456jain** [comment]
> can you show how it looks if img present?
> The height of the img is modified in CSS

should i add a random img from my system ?

**Comment by siv2r** [comment]
> should i add a random img from my system ?

Yes, you can modify the code below to point it to your own image.
https://github.com/siv2r/kidney-exchange/blob/738044907becf52b5fd4bf23b1d33d3bb721bf0c/pages/displayGlobalMatch.php#L17

**Comment by arpit456jain** [comment]
ssss

@siv2r it will look like some thing like this .
it will not affect footer

**Comment by siv2r** [comment]
Great! I will merge your PRs by evening :)

**Comment by arpit456jain** [comment]
ok @siv2r i am waiting .
as soon these PRs got merged i will start working on responsiveness on small screen

**Pull request merged**
