### PR TITLE
fixed the bug

### PR DESCRIPTION
**Pull request by arpit456jain**
navbar not working on pairData.php 

Fixes : #230

### CODE REVIEW

**Comment by siv2r** [comment]
How does adding a footer fix this issue?

**Comment by arpit456jain** [comment]
> How does adding a footer fix this issue?

The js link for working of navbar is in footer .
I placed it there so that it can be used easily

**Comment by siv2r** [comment]
ohh.. so in every page the footer has to be included then?

**Comment by arpit456jain** [comment]
> ohh.. so in every page the footer has to be included then?

Its already included

**Comment by arpit456jain** [comment]
> ohh.. so in every page the footer has to be included then?
In most of the pages its included

**Comment by arpit456jain** [comment]
That's why I ask you to double check whether navbar is working or not

**Comment by arpit456jain** [comment]
If its not working we just have to add one line of code

**Comment by arpit456jain** [comment]
In future if you want to any js script.
Will you add it to every page one by one?
No you just have to put that link in footer.php @siv2r

**Comment by arpit456jain** [comment]
All the js files should be end of the page just before

/Body
End of body tag

**Comment by siv2r** [comment]
Sure, I just wanted to confirm this

**Pull request merged**
