### PR TITLE
Added 404 page template

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### Any relevant logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### Any other comments?
....

### CODE REVIEW

**Comment by arpit456jain** [comment]
404 page

**Comment by arpit456jain** [comment]
@siv2r please review this PR

**Comment by siv2r** [comment]
@arpit456jain can you separate the css? You can put it in the file `404page.css`.

**Comment by arpit456jain** [comment]
> @arpit456jain can you separate the css? You can put it in the file `404page.css`.

ok @siv2r

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/120620876-0642e180-c47b-11eb-8012-79dc8306686f.mp4

@siv2r its done

**Review by riasenpai — APPROVED** [review]

**Pull request merged**
