### PR TITLE
made project setup documentation

### LINKED ISSUE #164: Create a document for setting up this project
Currently, this project has information about the project set up embedded in its [readme](https://github.com/siv2r/kidney-exchange#setting-up-this-project).

It would be nice if there is a separate document for this, and we can include this under the [documentation subsection of the readme](https://github.com/siv2r/kidney-exchange#documentation).

This is essential documentation so, make sure your PR is of good quality.

### PR DESCRIPTION
**Pull request by subhangi2731**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
I have made the documentation on how to the project setup 

### Does this close any currently open issues?
 Fixes  #164 

### How did you test your changes?
http://localhost/phpmyadmin/index.php
[sql notes.txt](https://github.com/siv2r/kidney-exchange/files/6522026/sql.notes.txt)

### CODE REVIEW

**Comment by subhangi2731** [comment]
@siv2r please review and merge my pr

**Review by siv2r — CHANGES_REQUESTED** [review]
- mention the fronteend method before the backend method.
- the database file to download is not shown properly.

**Comment by subhangi2731** [comment]
@siv2r please review and merge my pr

**Comment by subhangi2731** [comment]
@siv2r please merge my pr

**Comment by subhangi2731** [comment]
@siv2r can u please merge

**Comment by subhangi2731** [comment]
I did the changes

**Comment by siv2r** [comment]
@subhangi2731 sorry for the delay. 

The download option for the file does not seem to be there. Also, there are some inconsistencies with the headings. Can you just copy-past whatever was mentioned in the readme exactly?

**Comment by siv2r** [comment]
> The download option for the file does not seem to be there.

I think it is not possible to attach files on github readme

**Comment by subhangi2731** [comment]
@siv2r okay i will do this I just have to change the headings right other than that everything is correct? cause the attachment of download option is not possible in readme

**Comment by siv2r** [comment]
yes, just copy paste the things in readme exactly, that should work.

**Comment by subhangi2731** [comment]
@siv2r done please merge my pr

**Review by siv2r — APPROVED** [review]

**Pull request merged**
