### PR TITLE
home page is responsive now

### PR DESCRIPTION
**Pull request by arpit456jain**
# Changes
home page is responsive now

Fixed : #117 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://user-images.githubusercontent.com/55352601/116452299-347d4200-a87b-11eb-9d8a-9833c7103ce9.mp4

### CODE REVIEW

**Comment by siv2r** [comment]
Hey, I was planning to revert to the previous homepage since this page is not consistent with the project's theme.
Hence, I do not this it would be advisable to make it responsive now. Can you send the PR after reverting to the old homepage?
I will do the revert tomorrow.

**Comment by arpit456jain** [comment]
Ok

**Comment by siv2r** [comment]
You can simply edit this PR after the revert. Your work won't be wasted :)

**Comment by siv2r** [comment]
I reverted the home page to the old version.

**Comment by arpit456jain** [comment]
home page

is this ok ?? because there is no text.
only image is creating problem
image

**Comment by arpit456jain** [comment]
now its look like this

https://user-images.githubusercontent.com/55352601/116592063-2f80c700-a93d-11eb-9207-91c1a40be35e.mp4

**Comment by siv2r** [comment]
Looks good!

**Comment by siv2r** [comment]
Amazing work :tada: :tada:

**Pull request merged**
