### PR TITLE
fixed the navbar padding

### PR DESCRIPTION
**Pull request by arpit456jain**
fixed the navbar padding

Fixes : #205 
before
screencapture-localhost-kidney-exchange-2021-05-28-00_10_49

after
screencapture-localhost-kidney-exchange-2021-05-28-00_25_31

### CODE REVIEW

**Comment by siv2r** [comment]
**Suggested Changes**
- add padding btw the github icon and the copyright textt

**Comment by siv2r** [comment]
**Suggested Changes**
- add padding btw the github icon and the copyright textt

**Comment by arpit456jain** [comment]
> **Suggested Changes**
> 
> * add padding btw the github icon and the copyright textt

@siv2r this issue is for navbar 😅 
Please check the other issue for footer

**Comment by siv2r** [comment]
Ohh.. Sorry. Yep, do this for the footer one.

**Pull request merged**
