### PR TITLE
added a customizable message to issue assign bot

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
added a customizable message to issue assign bot

### Does this close any currently open issues?
Fixes : #142 

msg

### CODE REVIEW

**Comment by arpit456jain** [comment]
@priyanshuone6 is this ok ?

**Comment by priyanshuone6** [comment]
The user is not tagged in the comment, could you make those changes

**Comment by priyanshuone6** [comment]
@arpit456jain Looks good, thanks!

**Review by priyanshuone6 — APPROVED** [review]

**Comment by arpit456jain** [comment]
bot

**Comment by arpit456jain** [comment]
ok @priyanshuone6  
thanks :)

**Comment by arpit456jain** [comment]
> Can you change the name of the bot from `github-actions` to `Issue assigner`? Feel free to use another name if have one better that `Issue assigner`

@siv2r its name is already issue-assigner

**Comment by arpit456jain** [comment]
Its in the folder named .github

**Comment by arpit456jain** [comment]
And I don't think so if I put that file outside of that folder. Whether it will work or not

**Comment by siv2r** [comment]
Ohh.. so, the bot name ` github-actions` shown in comments can't be changed?

**Comment by arpit456jain** [comment]
Ah i don't think so i have to do a research on it for confirmation

**Comment by arpit456jain** [comment]
I will check it if its possible i will let you know and will make a PR for that :)

**Comment by siv2r** [comment]
> I will check it if its possible i will let you know and will make a PR for that :)

You can update this PR if that is possible.

**Comment by arpit456jain** [comment]
@siv2r currently i am working on more than 6 branches in this project its little bit tuff for me you can mention this issue desc may be someone can do it

**Pull request merged**
