### PR TITLE
changed hospital id to hospital name

### PR DESCRIPTION
**Pull request by simarjeet30**
edited the code to display hospital name instead of hospital id in PHP.

### CODE REVIEW

**Comment by siv2r** [comment]
@simarjeet30, were you able to test the changes? If so, a screenshot of the final result would be helpful.

**Comment by simarjeet30** [comment]
Umm the pull request could not clear all test cases.And I dont know what
was wrong in it .

**Comment by siv2r** [comment]
> Umm the pull request could not clear all test cases

Were you manually able to observe the 'hospital id' change to 'hospital name'? (ie, after setting up the project in your local machine). I am not talking about the tests ran on GitHub :)

**Comment by siv2r** [comment]
@simarjeet30, you can send a new PR after testing it. 
I am closing this due to inactivity.

**Pull request closed without merging**
