### PR TITLE
Changed URLs path

### PR DESCRIPTION
**Pull request by sahilempire**

### CODE REVIEW

**Comment by sahilempire** [comment]
HI @siv2r ,

I think, I have **done all things correctly** but still **getting this erro**r.
Please check this, and tell me **what I have to do next**.

Thanking you.

**Comment by siv2r** [comment]
@sahilempire did you read the description of this issue?

Also, it seems that you just simply deleted the code in a commit and added it back again in another.

**Comment by siv2r** [comment]
I updated the issue description recently. The changes must be made to the `architecture` branch, not `master`. I believe the `subpagesNavBar.php` should be present on the `architecture` branch.

**Comment by sahilempire** [comment]
What happend? @siv2r

**Comment by sahilempire** [comment]
okay, @siv2r but all should present in ` subpagesNavBar.php`

**Comment by sahilempire** [comment]
I have created another pull request [https://github.com/siv2r/kidney-exchange/pull/57](url) from `architecture` branch so I'm closing this pull request.

**Pull request closed without merging**
