### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

### What does this implement/fix? Explain your changes.
added footer

Fixes : #104 

screencapture-localhost-kidney-exchange-pages-signup-php-2021-05-16-19_55_02
screencapture-localhost-kidney-exchange-pages-signup-php-2021-05-16-19_54_44

### CODE REVIEW

**Comment by arpit456jain** [comment]
i can add other social media icons also like fb, whatsapp ,twitter etc and yeah there is an hovering effect on github icon
see this 

https://user-images.githubusercontent.com/55352601/118400903-3ae42a00-b681-11eb-9317-90e7d662010d.mp4

**Comment by siv2r** [comment]
Can you show how this footer works with other pages?

**Comment by arpit456jain** [comment]
yes

**Comment by arpit456jain** [comment]
fo

**Comment by arpit456jain** [comment]
thodi si css daalni pdegi bs accoring to page like isme background thoda light lg ra hai

**Comment by arpit456jain** [comment]
@siv2r layout will be the same on every page

**Review by siv2r — APPROVED** [review]

**Pull request merged**
