### PR TITLE
Solved issue #69 Limit Age Input 

### PR DESCRIPTION
**Pull request by Spurthi7768**
@siv2r  is the changes that I have made expected in this case? I am not sure.. I still think a validation method is necessary...
Address #69

### CODE REVIEW

**Comment by siv2r** [comment]
@Spurthi7768 will the user be able to see those options less than min data?
It is better to avoid the validation method since there are so many already. You can try something like [this](https://stackoverflow.com/questions/43274559/how-do-i-restrict-past-dates-in-html5-input-type-date)

**Comment by Spurthi7768** [comment]
@siv2r The user is not able to see options less than min data? Do I have to set max date also?

**Comment by siv2r** [comment]
> Do I have to set max date also?

As you have mentioned before, setting a max date does not make sense since a person may use this software in later years like 2022, 2023, etc.

**Comment by siv2r** [comment]
> You can check it once...

I will test this and let you know :)

**Comment by siv2r** [comment]
Hey, Sorry for not responding sooner. I am currently busy with GSoC :(
I will try to check the PR by this week.

**Comment by Spurthi7768** [comment]
@siv2r  Yeah, no issues! I too have my exams going on..so couldn't really follow up!

**Comment by Spurthi7768** [comment]
@siv2r  Any update?

**Comment by siv2r** [comment]
> @siv2r Any update?

Thanks for reminding me. I actually forgot abt this...lol
I will look into this tommorow.

**Comment by siv2r** [comment]
@Spurthi7768 The code changes seem correct.

I am sorry for not working on this. It has been a long time since I have last developed this project on my local machine. I am kind of reluctant to set up the environment and test this change before merging. If you add the way you test this change, I can merge this much faster. 

You can take #103 as an example for "How to add your test on the PR".

If not, I will definitely test this before GSSoC ends so that you don't lose your points. Also, I upgraded the issue by one level to compensate for the delay on my part :)

**Comment by Spurthi7768** [comment]
Donor_ss
patient_ss

**Comment by Spurthi7768** [comment]
@siv2r Actually I don't have any screen recording software..so I have attached the screenshots of the changes in the input form.. hope it helps.. if anything else you would like to know please let me know.

**Comment by siv2r** [comment]
> I don't have any screen recording software..

Screenshots are enough. 

This looks great. Can you manually type a date before 1951? Instead of selecting it.

**Comment by Spurthi7768** [comment]
type_ss

**Comment by Spurthi7768** [comment]
@siv2r Yes, the user can type a year before 1951 but it shows a warning/alert message and will not proceed further for submission as shown in the screenshot

**Comment by Spurthi7768** [comment]
@siv2r Is it okay to display a warning message then?

**Comment by siv2r** [comment]
> @siv2r Is it okay to display a warning message then?

Is it not displayed in the screenshot that you attached? (contains the warning message "Please enter a value greater than or equal to 1951-01-01")

**Comment by Spurthi7768** [comment]
@siv2r  Yes! Then is there any other changes I need to make?

**Comment by Spurthi7768** [comment]
@siv2r  Any update? Anything else required?

**Comment by siv2r** [comment]
Sorry for delaying the merge. Everything looks great!
Thanks for the contribution :tada: :tada:

**Pull request merged**
