### PR TITLE
added code to handle 404 error

### PR DESCRIPTION
**Pull request by arpit456jain**
added code to handle 404 error

FIxes : #241 

https://user-images.githubusercontent.com/55352601/120136745-7a1d8980-c1f0-11eb-952f-88647de8c314.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@siv2r please review this PR

**Comment by siv2r** [comment]
@arpit456jain can you put 404.php under the `pages/` directory?

**Comment by arpit456jain** [comment]
> @arpit456jain can you put 404.php under the `pages/` directory?

@siv2r yes i m on it

**Comment by arpit456jain** [comment]
@siv2r its done

**Comment by arpit456jain** [comment]
@siv2r can i make some PRs for adding the same back to top buttons in other pages which are long

**Comment by siv2r** [comment]
> @siv2r can i make some PRs for adding the same back to top buttons in other pages which are long

sure!

**Pull request merged**
