### PR TITLE
Overview section on home page

### PR DESCRIPTION
**Pull request by arpit456jain**
(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)
### What does this implement/fix? Explain your changes.

Overview section on home page

### Does this close any currently open issues?
Fixes : #170 

### How did you test your changes?

screencapture-localhost-kidney-exchange-2021-05-16-16_09_52
screencapture-localhost-kidney-exchange-2021-05-16-16_09_33

### CODE REVIEW

**Comment by arpit456jain** [comment]
@siv2r please review my PR

**Comment by siv2r** [comment]
Instead of explaining the project, we can write some catchy sentences on the homepage. Maybe add a nice picture (optional) along with it.  

For example, like the one here: https://www.kidney.org/donation?promo=MTL0001457
You can also google "kidney exchange programs" and keep their homage as a reference.

**Comment by arpit456jain** [comment]
Can i enhance it another issue ??

**Comment by siv2r** [comment]
> Can I enhance it another issue ?? Tomorrow..

This page looks good if left empty instead of a written paragraph.

**Comment by arpit456jain** [comment]
But then footer will not look good

**Comment by arpit456jain** [comment]
foot

**Comment by arpit456jain** [comment]
@siv2r It needs some content on that page so that footer can be at bottom

**Comment by arpit456jain** [comment]
If I fixed the footer at bottom then it will overlap on other pages , I had tried that also

**Pull request merged**
